### ISSUE TITLE
TerraformInstaller@0 does not support ARM64 builds

### ISSUE THREAD

**Issue by danieljurek** [microsoft/azure-pipelines-terraform#116]
When running the terraform installer task (as in this example) on an ARM64 build agent

```yaml
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    inputs:
      terraformVersion: "latest"
```

We get the following error: 

```
##[error]Error: Architecture arm64 is not supported
```

It looks like this can be fixed by adding support for `arm64` to this logic: https://github.com/microsoft/azure-pipelines-terraform/blob/main/Tasks/TerraformInstaller/src/terraform-installer.ts#L103-L114

In this case, I would expect `os.arch()` to return `arm64` which would map directly to creating the appropriate filename with the existing logic. https://releases.hashicorp.com/terraform/1.3.6/
