### ISSUE TITLE
TerraformTask init support for AzureAD Authentication access the Blob Storage Account

### ISSUE THREAD

**Issue by almir0** [microsoft/azure-pipelines-terraform#118]
I want to disable authentication with shared keys to storage account that I use for terraform backend, and terraform supports this by adding `use_azuread_auth` as described here: https://developer.hashicorp.com/terraform/language/settings/backends/azurerm#use_azuread_auth

TerraformTask should also support that

```
- task: TerraformTaskV2@2
              displayName: "Terraform : azurerm -> init"
              inputs:          
                provider: "azurerm"
                command: "init"
                workingDirectory: '$(Pipeline.Workspace)/$(artifactsName)/${{ parameters.tf_main_module }}'
                backendServiceArm: ${{ parameters.serviceConnectionName }}
                backendAzureRmResourceGroupName: $(backendAzureRmResourceGroupName)
                backendAzureRmStorageAccountName: $(backendAzureRmStorageAccountName)
                backendAzureRmContainerName: $(backendAzureRmContainerName)
                backendAzureRmKey: $(backendAzureRmKey)
                useAzureAdAuth: $(useAzureAdAuth) <-------------- SOMETHING LIKE THIS
```

**Comment by mericstam** [comment]
Hi, I will take a look at this.

**Comment by mericstam** [comment]
Not sure this will work as the extension only supports Authenticating with Service Principal.

**Comment by almir0** [comment]
> After some investigating, I am not sure this will work as the extension only supports Authenticating with Service Principal.

Thanks for looking into this. Would it be possible to implement support for AzureAD auth support?

**Comment by loopyd** [comment]
AzureAD is being deprecated, this isn't wise to implement.  Please see:   https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview , as MSA1 will become the standard soon.

Please use subscription scoped RBAC, choose "auto" mode, then move over to your tenant and add the SP to the subscription as "Contributor" -- Though I recommend you define a custom role (best practice) instead of Contributor, to scope down permissions, this gets it working.

⛔ Please do not leave it this way in production and scope down the SP's role in your subscription accordingly.

**Comment by Tolbin400** [comment]
> AzureAD is being deprecated, this isn't wise to implement. Please see: https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-overview , as MSA1 will become the standard soon.
> 
> Please use subscription scoped RBAC, choose "auto" mode, then move over to your tenant and add the SP to the subscription as "Contributor" -- Though I recommend you define a custom role (best practice) instead of Contributor, to scope down permissions, this gets it working.
> 
> > ⛔ Please do **NOT** give an app "Contributor" and leave it this way in production.  Scope down the SP's role in your subscription accordingly.

Hi AzureAD isn't being deprecated just the legacy AzureAD Graph API in favor of the new Microsoft Graph API which also uses AzureAD

The support for the use of Azure AD within the terraform init command when using azure storage for the backend is vital if you want to disable the use of shared keys on the target storage account as recommended by Microsoft.

**Comment by Tunderwood93** [comment]
@almir0 What you're trying to do can be accomplished by configuring your backend.tf file like so.

```
terraform {
    backend "azurerm" {
        storage_account_name = "StorageAccountNameHere"
        container_name       = "StorageAccountContainerNameHere"
        key                  = "NameOfStateFileHere"
        use_azuread_auth     = true
    }
}
```

Subsequently your ADO Pipeline Task will look like this 
```
                - task: TerraformTaskV4@4
                  displayName: "Terraform init"
                  inputs:
                    command: 'init'
                    backendServiceArm: ${{ parameters.bkServiceArm }}
                    backendAzureRmStorageAccountName: ${{ parameters.bkStorageAccountName }}
                    backendAzureRmResourceGroupName: ${{ parameters.bkResourceGroup }}
                    backendAzureRmContainerName: ${{ parameters.bkStorageContainer }}
                    backendAzureRmKey: ${{ parameters.bkKey }}
```
