### ISSUE TITLE
Allow terraform init to pull 'backend' info from terraform.backend config

### ISSUE THREAD

**Issue by wenesak** [microsoft/azure-pipelines-terraform#148]
Please allow to the terraform init command to optionally pull the backend info from the 'terraform.backend' block, as we  always like to have 1 source of truth and always should be the terraform configs.

the current task allows to initialized terraform using another task, but always shows an error when the terraform plan task runs if it wasn't initialized using the same terraform tasks to do the init (false positive),
a quick fix will be to suppress the error when terraform was initialized outside of these tasks, but native support to the task to pull the backend specifics from code will be ideal.

Example for backends 
>> aws <<
terraform {
  backend "s3" {
    bucket         = "<bucket name>"
    key            = "< terraform state file key/name>"
    region         = "us-east-2"
  }
}

>> azure <<
terraform {
  }
  backend "azurerm" {
    resource_group_name  = "< resource_group_name >"
    storage_account_name = "< storage account name >"
    container_name       = "terraformstate"         
    key                            = "< terraform state file key/name >" 
  }
}

```yml
#example yml pipeline to do a terraform plan for AWS in tis example we are doing a terraform init
# using the AWS shell, so it will alway pull the right details for the backend

trigger:
  branches:
    include:
    - none

variables:

stages:
- stage: terraform_plan
  displayName: terraform_plan
  jobs:
  - job: 'terraform_plan'
    displayName: 'terraform plan job'
    pool:
      name: xxxxxxxxxxxxxxxxxx
    steps:
    - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
      displayName: 'terraform init'
      inputs:
        awsCredentials: aws_2.0_shared_svc
        scriptType: inline
        inlineScript: >
          terraform init -upgrade=true -no-color -input=false
        disableAutoCwd: true
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform
    - task: TerraformTaskV2@2
      displayName: 'Terraform Plan'
      inputs:
        provider: aws
        command: 'plan'
        commandOptions: -no-color -input=false
        environmentServiceNameAWS: aws_2.0_sharedsvc
        workingDirectory: $(System.DefaultWorkingDirectory)/terraform
```

while the above pipeline works it always shows an error when doing the terraform plan (same if we are running an azure terraform pipeline and doing an init using the azure powershell task so we can pull backend  configs form the actual terraform code)

![terraforn-plan-error](https://github.com/microsoft/azure-pipelines-terraform/assets/28111142/79eda29e-354b-46c8-93f6-5ae94dadcbfb)
