### ISSUE TITLE
Terraform Apply results in "There was an error when attempting to execute the process"

### ISSUE THREAD

**Issue by jeroensmink98** [microsoft/azure-pipelines-terraform#149]
When trying to run `terraform apply` on a Ubuntu Hosted runner I get the following error 

`##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/1.4.6/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/1.4.6/x64/terraform ENOENT`

See the `log.txt` file

## Full YAML File

```yaml
- stage: prepare
  displayName: 'Prepare Infrastucture'
  jobs:
    - job: terraform
      displayName: 'Terraform'
      steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: 'Install Terraform latest'

          - task: Bash@3
            displayName: 'Terraform version'
            inputs:
              targetType: 'inline'
              script: |
                terraform version

          # TF Init
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
            displayName: 'Terraform : Init'
            inputs:
              workingDirectory: '$(System.DefaultWorkingDirectory)/azure-infrastructure/terraform'
              backendServiceArm: AzureServiceConnection2
              backendAzureRmResourceGroupName: 'RG
              backendAzureRmStorageAccountName: container
              backendAzureRmContainerName: tfstate
              backendAzureRmKey: 'KEY_REFERENCE'

          # TF Plan
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
            displayName: 'Terraform : Plan'
            inputs:
              command: plan
              workingDirectory: '$(System.DefaultWorkingDirectory)/azure-infrastructure/terraform'
              environmentServiceNameAzureRM: AzureServiceConnection2

          # TF Apply
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
            displayName: 'Terraform : Apply'
            inputs:
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/azure-infrastucture/terraform'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: AzureServiceConnection2
```

[log.txt](https://github.com/microsoft/azure-pipelines-terraform/files/11374514/log.txt)
