### ISSUE TITLE
Issue with local-exec - az login required

### ISSUE THREAD

**Issue by pinaki-accenture** [microsoft/azure-pipelines-terraform#162]
### I have an issue running the az cli script using local-exec provisioner.
**Receive the following error:
ERROR: Please run 'az login' to setup account**

Task snippet -
```
  - task: TerraformTaskV2@2
    displayName: 'Terraform apply TaskV2'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: $(workingDirectory)
      environmentServiceNameAzureRM: ${{ variables.azureServiceConnectionName }}
      backendServiceArm: ${{ variables.azureServiceConnectionName }}
      backendAzureRmResourceGroupName: ${{ variables.backendResourceGroupName }}
      backendAzureRmStorageAccountName: ${{ variables.backendStorageAccountName }}
      backendAzureRmContainerName: ${{ variables.backendContainerName }}
      backendAzureRmKey: $(backendAzureRmkey)
```

Terraform part :
```
resource "null_resource" "reset_password" {
  provisioner "local-exec" {
    command = <<-EOT
       az postgres flexible-server update --resource-group ${var.resource_group_name} --name ${azurerm_postgresql_flexible_server.psql.name} --admin-password "${var.credentials.password_secret_name}"
    EOT
  }
```

**Comment by pinaki-accenture** [comment]
Updated the task - 

```
  - task: TerraformTaskV4@4
    displayName: 'Terraform apply TaskV4'
    inputs:
      provider: 'azurerm'
```

Now I am getting a different error :

```
Code: AuthorizationFailed
│ Message: The client '******-*****-*******' with object id
│ '******-*****-*******' does not have authorization to
│ perform action 'Microsoft.DBforPostgreSQL/flexibleServers/read' over scope
│ '/subscriptions/*********/resourceGroups/*********/providers/Microsoft.DBforPostgreSQL/flexibleServers/pos-*********'
│ or the scope is invalid. If access was recently granted, please refresh
│ your credentials.

```

**Comment by mericstam** [comment]
Hi, running az  cli requires you to do az login before you can use the command on an azure resource.  the terraform extension does not do az login automatically.

**Comment by pinaki-accenture** [comment]
Thanks

**Comment by avanmalleghem** [comment]
@mericstam and so what is the best practice ? Add `az login ...` into the terraform script ?

**Comment by mericstam** [comment]
If you have a dependency on a az command in you terraform script
i would would add a script task with az login before the terraform task is executed

**Comment by Wikiwix** [comment]
If someone else needs this, this is how we solved it (with s Service Connection using *workload identity federation with openid connect*):

```yaml
- task: AzureCLI@2
  displayName: Extract Azure CLI credentials for local-exec in Terraform apply
  condition: ${{ eq(parameters.layer, 'applications') }}
  inputs:
    azureSubscription: <Enter your Azure Subscription or the name of your Service connection>
    scriptType: bash
    scriptLocation: inlineScript
    addSpnToEnvironment: true #  needed so the exported variables are actually set
    inlineScript: |
      echo "##vso[task.setvariable variable=servicePrincipalId]$servicePrincipalId"
      echo "##vso[task.setvariable variable=idToken;issecret=true]$idToken"
      echo "##vso[task.setvariable variable=tenantId]$tenantId"
- task: Bash@3
  # This needs to be an extra step, because AzureCLI runs `az account clear` at its end
  displayName: Log in to Azure CLI for local-exec in Terraform apply
  condition: ${{ eq(parameters.layer, 'applications') }}
  inputs:
    targetType: 'inline'
    script: >-
      az login
      --service-principal
      --username='$(servicePrincipalId)'
      --tenant='$(tenantId)'
      --federated-token='$(idToken)'
      --allow-no-subscriptions
```

If you are using a secret instead:

```yaml
- task: AzureCLI@2
  displayName: Extract Azure CLI credentials for local-exec in Terraform apply
  condition: ${{ eq(parameters.layer, 'applications') }}
  inputs:
    azureSubscription: <Enter your Azure Subscription or the name of your Service connection>
    scriptType: bash
    scriptLocation: inlineScript
    addSpnToEnvironment: true #  needed so the exported variables are actually set
    inlineScript: |
      echo "##vso[task.setvariable variable=servicePrincipalId]$servicePrincipalId"
      echo "##vso[task.setvariable variable=servicePrincipalKey ;issecret=true]$servicePrincipalKey "
      echo "##vso[task.setvariable variable=tenantId]$tenantId"
- task: Bash@3
  # This needs to be an extra step, because AzureCLI runs `az account clear` at its end
  displayName: Log in to Azure CLI for local-exec in Terraform apply
  condition: ${{ eq(parameters.layer, 'applications') }}
  inputs:
    targetType: 'inline'
    script: >-
      az login
      --service-principal
      --username='$(servicePrincipalId)'
      --tenant='$(tenantId)'
      --password='$(servicePrincipalKey)'
      --allow-no-subscriptions
```
