### ISSUE TITLE
state command not working

### ISSUE THREAD

**Issue by abhiramani-git** [microsoft/azure-pipelines-terraform#207]
this is the task i am running. i keep getting this error:State management commands require a state file. Run this commandto point the command to a specific state location.

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : azurerm'
  inputs:
    command: custom
    customCommand: state
    commandOptions: 'list -state=https://teststorageaccount.blob.core.windows.net/ahs-tfstate/azure-terraform/VulnerabilitiesReporting/02_others/devtest/devtest.tfvars'
    environmentServiceNameAzureRM: 'MyConnection'
  enabled: false

**Comment by mericstam** [comment]
Hi, first of all what are you trying to accomplish? And is your state file called devtest.tfvars?
please provide the steps of your pipeline.

br
Manuel

**Comment by abhiramani-git** [comment]
i am trying to list state file content and hhen i need to delete some resources from state file

yes its called devtest.tfvars. i have just kept that extension instead of .tfstate

**Comment by mericstam** [comment]
Do you use SAS token to access blob store? or how do you authenticate?

/Manuel

**Comment by abhiramani-git** [comment]
Hi i am running pipeline using service principal and it has contributor access to storage account. and other steps like terraform init/plan/apply all work fine. just state commands like list/rm not working

**Comment by mericstam** [comment]
as far as I understand the option -state=path is ignored when using remote state.

https://developer.hashicorp.com/terraform/cli/commands/state/list
 So perhaps as a test you can change to default name?

br
Manuel

**Comment by abhiramani-git** [comment]
Just terraform state list fails with not much info. my state is already successfully initialized in "terraform init state"
<img width="1051" alt="Screen Shot 2024-01-29 at 8 28 07 PM" src="https://github.com/microsoft/azure-pipelines-terraform/assets/91931006/0e8eeffa-a271-42ad-b3db-31a48341f59a">

**Comment by abhiramani-git** [comment]
Any update?

**Comment by mericstam** [comment]
Hi,  do you run above state step  in a separate job from terrafom init?

**Comment by mericstam** [comment]
Can you run the terraform state command locally?

**Comment by mericstam** [comment]
Hi, sorry for late reply. do you still have issues?
If so please provide the steps of your pipeline. ( i.e yaml code )

br
Manuel

**Comment by RLashofRegas** [comment]
I am having the same issue. Pipeline YAML:
```
          - task: TerraformTaskV4@4
            displayName: Terraform Custom Command
            inputs:
              provider: aws
              command: custom
              customCommand: ${{ parameters.terraform_command }}
              backendServiceAWS: ${{ parameters.tf_connector }}
              backendAWSKey: ${{ parameters.tf_key }}
              workingDirectory: "$(System.DefaultWorkingDirectory)/infra"
              environmentServiceNameAWS: ${{ parameters.tf_connector }}
              backendAWSBucketName: ${{ parameters.tf_bucket }}
```

When I pass `terraform_command` as `state list` (or any other state command) I get the following output

```
/usr/local/bin/terraform state list
Usage: terraform [global options] <subcommand> [args]

The available commands for execution are listed below.
  get           Install or upgrade remote Terraform modules
  graph         Generate a Graphviz graph of the steps in an operation
  import        Associate existing infrastructure with a Terraform resource
  login         Obtain and save credentials for a remote host
  logout        Remove locally-stored credentials for a remote host
  metadata      Metadata related commands
  modules       Show all declared modules in a working directory
  output        Show output values from your root module
  providers     Show the providers required for this configuration
  refresh       Update the state to match remote systems
  show          Show the current state or a saved plan
  state         Advanced state management
  taint         Mark a resource instance as not fully functional
  test          Execute integration tests for Terraform modules
  untaint       Remove the 'tainted' state from a resource instance
  version       Show the current Terraform version
  workspace     Workspace management

Global options (use these before the subcommand, if any):
  -chdir=DIR    Switch to a different working directory before executing the
                given subcommand.
  -help         Show this help output, or the help for a specified subcommand.
  -version      An alias for the "version" subcommand.

##[error]Error: The process '/usr/local/bin/terraform' failed with exit code 127

```

terraform plan task is working fine.
