### ISSUE TITLE
Azure SQL database management using Workload Identity Federation service connection in Azure DevOps

### ISSUE THREAD

**Issue by mkrieger2468** [microsoft/azure-pipelines-terraform#217]
I am unable to manage a database using provider pgssoft/mssql with the Terraform task.  I get the following error message when I use that provider.  Everything else works when you set the environment variable `ARM_USE_AZUREAD`.  I found if you follow Microsoft documentation and run the azureCLI command `az account get-access-token`, it will work.

Error message:
```
│ DefaultAzureCredential: failed to acquire a token.
│ Attempted credentials:
│ 	EnvironmentCredential: missing environment variable AZURE_CLIENT_ID
│ 	ManagedIdentityCredential: no default identity is assigned to this
│ resource
│ 	AzureCLICredential: ERROR: Please run 'az login' to setup account.
```
Terraform Task:
```
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    command: plan
    workingDirectory: '$(terraformWorkingDirectory)'
    commandOptions: -var-file="$(terraformWorkingDirectory)\tfvars\${{ parameters.Environment }}.tfvars" -out="$(Agent.TempDirectory)\tfplan"
    environmentServiceNameAzureRM: '$(ServiceConnectionName)'
  env:
    ARM_USE_AZUREAD: true
```

AzureCLI Task:
```
- task: AzureCLI@2
  displayName: Terraform Plan
  inputs:
    azureSubscription: $(ServiceConnectionName)
    scriptType: pscore
    scriptLocation: inlineScript
    scriptPath: $(terraformWorkingDirectory)
    inlineScript: |
      az account get-access-token | Out-Null
      $terraform = Get-Command terraform
      & $terraform -chdir="$(terraformWorkingDirectory)" plan -var-file="$(terraformWorkingDirectory)\tfvars\${{ parameters.Environment }}.tfvars" -out="$(Agent.TempDirectory)\tfplan"
  env:
    ARM_USE_AZUREAD: true
```
