### ISSUE TITLE
`output` tasks still logs to console despite `output: 'file'` option

### ISSUE THREAD

**Issue by samcarswell** [microsoft/azure-pipelines-terraform#227]
We're using the below to output `terraform output` to a file:
```yml
  - task: TerraformTaskV4@4
    displayName: terraform output
    inputs:
      provider: 'azurerm'
      command: 'output'
      outputTo: 'file'
      workingDirectory: ${{parameters.workingDirectory}}
      environmentServiceNameAzureRM: $(azureConnection)
    name: TerraformOutput
```

This works, however it also prints the terraform output to the console in addition to the file, which I would not expect.
This is especially a problem if the terraform output values contain secrets, as these are displayed in plain text

**Comment by Midnighter** [comment]
While I completely agree with the sentiment, I also want output written to file only and parse from there, the docs are quite clear that `outputTo` can only be used with the `show` or `custom` commands.

> Options specific to show
>
> outputTo*: (console or file). You can choose to save output to file or only show output in console (i.e log)
outputFormat*: (json or default) . Output in json or default format

> Options specific to custom
When selecting custom you can use any command that is supported natively by terraform.
>
> customCommand*: pass any command that is supported natively by terraform
outputTo*: (console or file).You can choose to save output to file or only show output in console (i.e log)

**Comment by Midnighter** [comment]
Just to be clear, you can achieve the desired behavior with the following code, but I agree with OP that hiding console output would provide clearer semantics.

```yaml
      - task: TerraformTaskV4@4
        name: terraformOutput
        displayName: Write Terraform Output Variables
        inputs:
          command: custom
          customCommand: output
          commandOptions: -json
          outputTo: file
```

You can then access that file with `terraformOutput.customFilePath`.

**Comment by stehubhex** [comment]
Hi , I am using a the custom command and have outputTo: 'file' but I cant see a file being created. Is it outputting it to the same directory or a different one ?

**Comment by sandra-bee** [comment]
> While I completely agree with the sentiment, I also want output written to file only and parse from there, the docs are quite clear that `outputTo` can only be used with the `show` or `custom` commands.
> 
> > Options specific to show
> > outputTo*: (console or file). You can choose to save output to file or only show output in console (i.e log)
> > outputFormat*: (json or default) . Output in json or default format
> 
> > Options specific to custom
> > When selecting custom you can use any command that is supported natively by terraform.
> > customCommand*: pass any command that is supported natively by terraform
> > outputTo*: (console or file).You can choose to save output to file or only show output in console (i.e log)

The same behaviour is observed with the `show` command; despite setting `outputTo`, the plan is written to both file and console.

**Comment by virgolee2209** [comment]
> Hi , I am using a the custom command and have outputTo: 'file' but I cant see a file being created. Is it outputting it to the same directory or a different one ?

Hi all, I am also trying to output to a separate json file but cant file it anywhere. If I run local using terraform command directly then it works but no luck using TerraformTask@5 in AzurePipelines. I also tried using custom command with something like "output -json > tf_outputs.json" but the the command is not recognized and throws error code 127.

Has anyone make it to work? Apply then output to json file so data is available for the next stage to use.

Thanks,

**Comment by stehubhex** [comment]
@virgolee2209  I did change the functionality of the script so i can adapt and go around that , but I currently use this :
```yml

    - task: TerraformTaskV4@4
      displayName: TF Plan output to file
      inputs:
        provider: 'azurerm'
        command: 'custom'
        customCommand: 'plan'
        commandOptions: '--var-file=${{ parameters.TFvarFile }} -no-color -input=false -out=tfplan'
        environmentServiceNameAzureRM: ${{ parameters.ServiceConnection }}
        workingDirectory: '${{ parameters.TerraformWorkDir }}'
  
    - task: Bash@3
      displayName: 'Get TF View txt'
      inputs:
        workingDirectory: '${{ parameters.TerraformWorkDir }}'
        targetType: 'inline'
        script: |
          terraform show -no-color tfplan > $(Build.ArtifactStagingDirectory)/driftview.txt

```

This will output a tfplan and then using the terraform show command I output that to a txt file that then I can read and work with as I need .

Hope it helps

**Comment by john-edwin-braun** [comment]
I want to add to this issue. We need the terraform output as pipeline variables. But when using the following task the outputs also get written to the log and secrets are not masked. I did not find any way to suppress the secrets/log.

```
  - task: TerraformTask@5
    displayName: "Terraform Variables Output"
    name: tf_output
    inputs:
      command: output
      workingDirectory: ${{ parameters.terraformWorkingDirectory }}
      environmentServiceNameAzureRM: ${{ parameters.environmentServiceName }}
      outputTo: file
      outputFormat: json
```
