### ISSUE TITLE
TerraformTaskV4@4 fails on Azure pipelines with image ubuntu-latest

### ISSUE THREAD

**Issue by CharanGali** [microsoft/azure-pipelines-terraform#228]
Team,

Could you please help us in resolving the below error while initialising the terraform on ubuntu machine in pipelines.
![image](https://github.com/user-attachments/assets/c03135e3-bf6a-4cc4-93aa-96774c1fb1df)
![image](https://github.com/user-attachments/assets/d1e4eded-8a1a-4553-84b7-3042de12e170)

**Comment by mericstam** [comment]
Hi, sorry for late reply,  do you still have issues? Br Manuel

**Comment by CharanGali** [comment]
Yes @mericstam 
Could you please help us ?

**Comment by mericstam** [comment]
please supply the full line in light blue from your screenshot.  and if possible supply the part of the pipeline where the init command is declared.

**Comment by CharanGali** [comment]
@mericstam 

> please supply the full line in light blue from your screenshot. and if possible supply the part of the pipeline where the init command is declared.

Not only with the init command. If we use the validate command as well, i was receiving error as below
![image](https://github.com/user-attachments/assets/5060241a-b6d9-4fc2-8250-aa9bc20ed7da)
i.e., ##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/1.9.4/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/1.9.4/x64/terraform ENOENT

But in previous step, i can terraform is installed as expected
![image](https://github.com/user-attachments/assets/ae713f26-54d1-4e5b-8fbc-144c42b5ddd1)


Please let me know if you need additional details

**Comment by CharanGali** [comment]
@mericstam 

Same issue happening with windows image also.
`##[error]Error: There was an error when attempting to execute the process 'C:\hostedtoolcache\windows\terraform\1.9.5\x64\terraform.exe'. This may indicate the process failed to start. Error: spawn C:\hostedtoolcache\windows\terraform\1.9.5\x64\terraform.exe ENOENT`
Could you please help ?

**Comment by mnelsonwhite** [comment]
Did you get anywhere with this? I have the same problem.

**Comment by Mirciulica15** [comment]
### I encountered the same error for TerraformTask@5 today.

```
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(terraformVersion)

- task: TerraformTask@5
  displayName: "Terraform Init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
    backendServiceArm: $(azureSubscription)
    backendAzureRmResourceGroupName: $(backendResourceGroupName)
    backendAzureRmStorageAccountName: $(backendStorageAccountName)
    backendAzureRmContainerName: $(backendContainerName)
    backendAzureRmKey: $(backendKey)
```

### Terraform Installer works properly:

```
Starting: TerraformInstaller
==============================================================================
Task         : Terraform tool installer
Description  : Find in cache or download a specific version of Terraform and prepend it to the PATH
Version      : 1.216.35
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AAf1a0p)
==============================================================================
Downloading: https://releases.hashicorp.com/terraform/1.11.3/terraform_1.11.3_linux_amd64.zip
Extracting archive
/usr/bin/unzip /home/vsts/work/_temp/terraform-1.11.3-b832f8bb-60f1-4d92-93e0-d1c60c59ec8f.zip
Archive:  /home/vsts/work/_temp/terraform-1.11.3-b832f8bb-60f1-4d92-93e0-d1c60c59ec8f.zip
  inflating: LICENSE.txt             
  inflating: terraform               

Caching tool: terraform 1.11.3 x64
Prepending PATH environment variable with directory: /opt/hostedtoolcache/terraform/1.11.3/x64
Verifying Terraform installation...
/opt/hostedtoolcache/terraform/1.11.3/x64/terraform version
Terraform v1.11.3
on linux_amd64

Finishing: TerraformInstaller
```

### However, TerraformTask@5 fails at the next step:

```
Starting: Terraform Init
==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on Microsoft Azure, Amazon Web Services(AWS), Google Cloud Platform(GCP) and Oracle Cloud Infrastructure(OCI). v5.255.1
Version      : 5.255.35
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/devlabs/ado/tf/task/v5)
==============================================================================
##[warning]Client secret authentication is not secure and will be deprecated in the next major version of this task. Please use Workload identity federation authentication instead.
/opt/hostedtoolcache/terraform/1.11.3/x64/terraform init -backend-config=storage_account_name=<hidden> -backend-config=container_name=<hidden> -backend-config=key=<hidden> -backend-config=resource_group_name=<hidden> -backend-config=subscription_id=<hidden> -backend-config=use_azuread_auth=true
##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/1.11.3/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/1.11.3/x64/terraform ENOENT

Finishing: Terraform Init
```

**##[error]Error: There was an error when attempting to execute the process '/opt/hostedtoolcache/terraform/1.11.3/x64/terraform'. This may indicate the process failed to start. Error: spawn /opt/hostedtoolcache/terraform/1.11.3/x64/terraform ENOENT**

### Additional info:

For this job I am using an environment with approvals, since an **apply** follows after the **init**.

```
jobs:
  - deployment: <hidden>
    displayName: <hidden>
    environment: <hidden>
    strategy:
      runOnce:
        deploy:
          steps:
            - task: TerraformInstaller@1
              inputs:
                terraformVersion: $(terraformVersion)
```
