### ISSUE TITLE
terraform show is not a command

### ISSUE THREAD

**Issue by pajcarpentier** [microsoft/azure-pipelines-terraform#23]
i Have this yaml template using the terraform task extension 

```
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
  name: terraform_${{ parameters.terraformCommand }}
  displayName: 'Terraform ${{ parameters.terraformCommand }}'
  inputs:
    command: ${{ parameters.terraformCommand }}
    workingDirectory: '${{ parameters.pathToTerraformRootModule }}'
    commandOptions: ${{ parameters.terraformCommandOptions }}
    environmentServiceNameAzureRM: '${{ parameters.serviceConnection }}'
    backendServiceArm: '${{ parameters.serviceConnection }}'
    backendAzureRmResourceGroupName: '${{ parameters.storageAccountResourceGroup }}'
    backendAzureRmStorageAccountName: '${{ parameters.storageAccount }}'
    backendAzureRmContainerName: '${{ parameters.stateBlobContainer }}'
    backendAzureRmKey: '${{ parameters.stateContainer }}'

```

I use it to -out=tfplan a terraform plan, and wanted to show the tfplan as json file to compare different plans between terraform versions.

```
               - template: ../templates/terraform.yaml
                  parameters:
                    terraformCommand: "plan"
                    terraformCommandOptions: "-lock=false -out=$(System.DefaultWorkingDirectory)/tfplan"
                    pathToTerraformRootModule: "$(pathToTerraformRootModule)"
                    serviceConnection: "$(serviceConnection)"
                    storageAccountResourceGroup: "$(storageAccountResourceGroup)"
                    storageAccount: "$(storageAccount)"
                    stateContainer: "$(MODULE)-$(TF_VAR_APPLICATION)-${{ parameters.Environment }}.tfstate"
                    stateBlobContainer: "$(stateBlobContainer)"

```

                - template: ../templates/terraform.yaml
                  parameters:
                    terraformCommand: "show"
                    terraformCommandOptions: "-json $(System.DefaultWorkingDirectory)/tfplan > $(Build.ArtifactStagingDirector)/tfplan.json"
                    pathToTerraformRootModule: "$(pathToTerraformRootModule)"
                    serviceConnection: "$(serviceConnection)"
                    storageAccountResourceGroup: "$(storageAccountResourceGroup)"
                    storageAccount: "$(storageAccount)"
                    stateContainer: "$(MODULE)-$(TF_VAR_APPLICATION)-${{ parameters.Environment }}.tfstate"
                    stateBlobContainer: "$(stateBlobContainer)"

Expected result is the tfplan.json is created for further use.

Actual result is bellow :

```
Starting: Terraform show
==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP)
Version      : 2.188.1
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/AA5j5pf)
==============================================================================
peError: provider[command] is not a function
Finishing: Terraform show

```

Does the terraform show command taken in account ?

**Comment by mericstam** [comment]
A version V3 is on its way. No ETA but soon

**Comment by vanmash** [comment]
@mericstam do you mind sharing a link to the new repo?

**Comment by mericstam** [comment]
V3 is now deployed in version 0.1.17 on the Marketplace. Give it a go and let me know what you think.

**Comment by mloskot** [comment]
@mericstam I can confirm the `show` works. Here is sample how I use it:

```yaml
- task: TerraformTaskV3@3
  displayName: 'Show Terraform Plan - ${{ environment }} - ${{ component }} '
  inputs:
    provider: 'azurerm'
    command: 'show'
    commandOptions: '-no-color $(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan'
    workingDirectory: 'infrastructure/stack/${{ component }}'
    outputTo: 'file'
    fileName: '$(System.DefaultWorkingDirectory)/$(Build.BuildId)_${{ component }}.plan.log'
    environmentServiceNameAzureRM: $(azureSubscription)

- task: TerraformTaskV3@3
  displayName: 'Show Terraform Plan JSON - ${{ environment }} - ${{ component }} '
  inputs:
    provider: 'azurerm'
    command: 'show'
    commandOptions: '-no-color -json $(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan'
    workingDirectory: 'infrastructure/stack/${{ component }}'
    outputTo: 'file'
    fileName: '$(System.DefaultWorkingDirectory)/$(Build.BuildId)_${{ component }}.plan.json'
    environmentServiceNameAzureRM: $(azureSubscription)
```
