### ISSUE TITLE
Terraform CLI task ignores ENV variables. 

### ISSUE THREAD

**Issue by kivio** [microsoft/azure-pipelines-terraform#238]
When I try to deliver ENV variables for terraform that are accepted only trough environment variables it looks like it was ignored:

```
- task: TerraformCLI@1
            name: terraformPlan
            displayName: Plan
            env:
              DYNATRACE_ENV_URL: "${{ variables.dtEnvUrl }}"
              DT_CLIENT_ID: "${{ variables.dtClientId }}"
              DT_ClIENT_ACCOUNT_ID: "${{ variables.dtAccountId }}"
              DYNATRACE_API_TOKEN: "${{ variables.dtApiToken }}"
              DT_CLIENT_SECRET: "${{ variables.dtClientSecret }}"
            inputs:
              workingDirectory: "$(System.DefaultWorkingDirectory)"
              command: "plan"
              commandOptions: "--out=main.tfplan -detailed-exitcode"
              environmentServiceName: "${{ variables.serviceConnectionName }}"
              publishPlanResults: "PlanView"
```

![image](https://github.com/user-attachments/assets/ae9375cb-907e-426b-80a7-87399b60eb1a)

In this case, maybe it can be fixed using terraform provider attributes, as suggested in issue. 
However, CLIENT related parameters are not supported through terraform providers attributes, and only environment configuration will work.
