### ISSUE TITLE
Cannot auth to Databricks provider over AZDO Federated Service Connection

### ISSUE THREAD

**Issue by nonamecoder2002** [microsoft/azure-pipelines-terraform#259]
Hello. We have encountered an issue with auth into Databricks workspace over Federated Service Connection.

Databricks provider configuration: 

```
provider "databricks" {
  host                        = azurerm_databricks_workspace.data_hub_dbw.workspace_url
  azure_workspace_resource_id = azurerm_databricks_workspace.data_hub_dbw.id
  # azure_use_msi = true
}

```
Pipeline task .yaml

```
steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
  displayName: 'Terraform : azurerm : plan'
  inputs:
    command: plan
    workingDirectory: '$(System.DefaultWorkingDirectory)/<PathToTerraformModule>'
    commandOptions: '-var-file=./$(component)-$(environment).tfvars '
    environmentServiceNameAzureRM: '<ServiceConnection>'
    backendAzureRmUseEnvironmentVariablesForAuthentication: false
    backendAzureRmUseEntraIdForAuthentication: true

```

Error we are getting:

```
2024-11-07T14:41:17.0769966Z Error: cannot read instance pool: failed during request visitor: default auth: azure-cli: cannot get account info: exit status 1. Config: host=<DatabricksWorkspaceURL>, azure_workspace_resource_id=<ResourseID>, azure_client_id=***, azure_tenant_id=<TenantID>. Env: ARM_CLIENT_ID, ARM_TENANT_ID
```
