### ISSUE TITLE
After successful init, receive error 'parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.' in plan task

### ISSUE THREAD

**Issue by aaearon** [microsoft/azure-pipelines-terraform#260]
In my deploy stage, after a successful `init` task, the `plan` task results in the following error:

Planning failed. Terraform encountered an error while generating this plan.

```
╷
│ Error: building AzureRM Client: obtain subscription(xxxxxxx) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 17, in provider "azurerm":
│   17: provider "azurerm" {
│ 
╵
```

Here is the relevant stage from my `azure-pipelines.yml`

```yaml
  - stage: terraformDeploy
    displayName: Deploy Terraform Plan
    condition: succeeded('terraformValidate')
    dependsOn: terraformValidate

    jobs:
      - job: apply
        displayName: Apply
        steps:
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: "azurerm"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/deploy/shared-resources/"
              backendServiceArm: "$(AZ_TERRAFORM_STATE_SERVICE_CONNECTION)"
              backendAzureRmResourceGroupName: "$(AZ_TERRAFORM_STATE_RESOURCE_GROUP)"
              backendAzureRmStorageAccountName: "$(AZ_TERRAFORM_STATE_STORAGE_ACCOUNT)"
              backendAzureRmContainerName: "$(AZ_TERRAFORM_STATE_CONTAINER)"
              backendAzureRmKey: "$(AZ_TERRAFORM_STATE_KEY)"
          - task: TerraformTaskV4@4
            name: terraformPlan
            displayName: plan
            env:
              # These need to be explicitly mapped
              # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash#secret-variable-in-the-ui
              SDM_API_ACCESS_KEY: $(SDM-API-ACCESS-KEY)
              SDM_API_SECRET_KEY: $(SDM-API-SECRET-KEY)
            inputs:
              provider: "azurerm"
              command: "plan"
              commandOptions: "-out main.tfplan"
              workingDirectory: "$(System.DefaultWorkingDirectory)/deploy/shared-resources/"
              environmentServiceNameAzureRM: "$(AZ_TERRAFORM_STATE_SERVICE_CONNECTION)"
          - task: TerraformTaskV4@4
            displayName: apply
            condition: eq(variables['terraformPlan.changesPresent'], 'true')
            env:
              # These need to be explicitly mapped
              # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash#secret-variable-in-the-ui
              SDM_API_ACCESS_KEY: $(SDM-API-ACCESS-KEY)
              SDM_API_SECRET_KEY: $(SDM-API-SECRET-KEY)
            inputs:
              provider: "azurerm"
              command: "apply"
              commandOptions: "main.tfplan"
              workingDirectory: "$(System.DefaultWorkingDirectory)/deploy/shared-resources/"
              environmentServiceNameAzureRM: "$(AZ_TERRAFORM_STATE_SERVICE_CONNECTION)"
```

The Azure RM service connection that is defined as the value for `environmentServiceNameAzureRM` has the Contributor role for the subscription though I am not sure that this is relevant.

**Comment by aaearon** [comment]
I solved this. My Azure RM service connection is using Workload dentity federation as the credential, which does not seem to be fully supported (?) as per #217. I recreated the service connection in my project and used Secret as the credential and the plan task executed without any error.

**Comment by redx177** [comment]
Had the same error message and could make it work with federated identity.
You need to configure terraform to use OpenID connect (OIDC). 

In terraform, you configure the `azurerm` provider to connect to azure. OIDC support has been added in 3.7.0. So >=3.7.0 is required. See https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_oidc
```
required_providers {
  azurerm = {
    source  = "hashicorp/azurerm"
    version = ">=3.7.0"
  }
}
```

Then `azurerm` has different authentication methods and needs to be configure to use OIDC.
See https://developer.hashicorp.com/terraform/language/backend/azurerm
`use_oidc` needs to be set to true, and depending on your usecase `use_azuread_auth` as well.
I set it via an environment variable in the pipeline:
```
- task: TerraformTaskV4@4
  displayName: Terraform apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: your-service-connection-with-federated-identity
  env:
    ARM_USE_AZUREAD: true
    ARM_USE_OIDC: true
```

I also think you need to use V4 of the task. Previous versions do not support federated identities.
