### ISSUE TITLE
Terraform output fails when providing argument

### ISSUE THREAD

**Issue by rfrerebe-stx** [microsoft/azure-pipelines-terraform#269]
Terraform will fail when providing argument

```
    - task: TerraformTaskV4@4
      displayName: "Terraform output"
      inputs:
        provider: 'azurerm'
        command: 'output'
        commandOptions: 'token'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
```

Error :

```
Starting: Terraform output
==============================================================================
Task         : Terraform
Description  : Execute terraform commands to manage resources on AzureRM, Amazon Web Services(AWS) and Google Cloud Platform(GCP). v4.241.11
Version      : 4.241.33
Author       : Microsoft Corporation
Help         : [Learn more about this task](https://aka.ms/devlabs/ado/tf/task/v4)
==============================================================================
/opt/hostedtoolcache/terraform/1.10.1/x64/terraform output token -json
╷
│ Error: Unexpected argument
│ 
│ The output command expects exactly one argument with the name of an output
│ variable or no arguments to show all outputs.
╵

For more help on using this command, run:
  terraform output -help
Finishing: Terraform output
```

Work around use `custom` command

```
    - task: TerraformTaskV4@4
      displayName: "Terraform output"
      inputs:
        provider: 'azurerm'
        command: 'custom'
        commandOptions: 'output token'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
```
