### ISSUE TITLE
Suggestion to change example to include "succeeded()" in example to not get stuck while pipeline is cancelled

### ISSUE THREAD

**Issue by tonur** [microsoft/azure-pipelines-terraform#272]
In the [README.md#example-task-usage](https://github.com/microsoft/azure-pipelines-terraform/blob/main/Tasks/TerraformTask/TerraformTaskV4/README.md#example-task-usage) file, it shows the following task:
```yaml
...
# Only runs if the 'terraformPlan' task has detected changes the in state. 
- task: TerraformTaskV4@4
  displayName: Apply Terraform Plan
  condition: eq(variables['terraformPlan.changesPresent'], 'true')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'main.tfplan'
    environmentServiceNameAzureRM: 'your-environment-service-connection'
```
The condition here is actually overwriting the default condition of "condition: succeeded()", which gets constantly evaluated to check fx if the Azure Pipeline is cancelled. The default can be seen documented here: [https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops#:~:text=by%20default%2C%20stages%2C%20jobs%2C%20and%20steps%20run%20if%20all%20direct%20and%20indirect%20dependencies%20succeed.%20this%20status%20is%20the%20same%20as%20specifying%20condition%3A%20succeeded().%20for%20more%20information%2C%20see%20succeeded%20status%20function.)
So by overwriting it to "eq(variables['terraformPlan.changesPresent'], 'true')", you effectively ensure that this task continues running even if the Azure Pipeline is cancelled.
I wrote about this in one of the easily searched topics here: https://old.reddit.com/r/azuredevops/comments/1dj0jlg/pipeline_job_wont_cancel/lr87z6b/.

Since this is super easy to overlook, I would like to propose changing the above example to be:

```yaml
...
# Only runs if the 'terraformPlan' task has detected changes the in state. 
- task: TerraformTaskV4@4
  displayName: Apply Terraform Plan
  condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'main.tfplan'
    environmentServiceNameAzureRM: 'your-environment-service-connection'
```

In my own repository, I have added a comment explaining why:
`# Needs a "succeeded()" condition, else the pipeline cannot be cancelled, see: https://old.reddit.com/r/azuredevops/comments/1dj0jlg/pipeline_job_wont_cancel/lr87z6b/`
But I would not think this is necessary, the implementer can be the judge of this.

This means the whole code section at the bottom of https://github.com/microsoft/azure-pipelines-terraform/blob/main/Tasks/TerraformTask/TerraformTaskV4/README.md#example-task-usage would look like this:
```yaml
- task: TerraformTaskV4@4
  displayName: Initialize Terraform
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'your-backend-service-connection'
    backendAzureRmResourceGroupName: 'your-rg-name'
    backendAzureRmStorageAccountName: 'your-stg-name'
    backendAzureRmContainerName: 'your-container-name'
    backendAzureRmKey: 'state.tfstate'

- task: TerraformTaskV4@4
  name: terraformPlan
  displayName: Create Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out main.tfplan'
    environmentServiceNameAzureRM: 'your-environment-service-connection'

# Only runs if the 'terraformPlan' task has detected changes the in state. 
- task: TerraformTaskV4@4
  displayName: Apply Terraform Plan
  condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'main.tfplan'
    environmentServiceNameAzureRM: 'your-environment-service-connection'
´´´
