### ISSUE TITLE
TerraformTaskV4@4 task: backendServiceArm or environmentServiceNameAzureRM must be hardcoded

### ISSUE THREAD

**Issue by Sebastiencreoff** [microsoft/azure-pipelines-terraform#274]
Hello,

I am writing a generic step which use terraformV4@4 task to init, plan and apply a terraform code. Within this stage, I would like to be able to provide as a group variable the backendServiceArm or environmentServiceNameAzureRM but each time, I have an issue with it:

Code example:
```
---
parameters:
  - name: environment
    displayName: Environment name
    type: string
    default: tst
  - name: variableGroupName
    displayName: Variable group name to use
    type: string

stages:

  - stage: ci
    displayName: "CI Pipeline"
    variables:
      - group: ${{ parameters.variableGroupName }}
    jobs:
      - job: setup
        displayName: Setup
        
        steps:
          - checkout: none
          
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: Install Terraform ${{ variables.COMMON_TERRAFORM_VERSION }}
            inputs:
              terraformVersion: ${{ variables.COMMON_TERRAFORM_VERSION }}
              
      - job: Plan
        dependsOn: setup
        displayName: Terraform Plan
        steps:
          - checkout: self

          - task: TerraformTaskV4@4
            displayName: Initialize Terraform
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: $(AZ_SERVICE_CONNECTION)
              backendAzureRmResourceGroupName: $(BACKEND_AZURE_RESOURCE_GROUP_NAME)
              backendAzureRmStorageAccountName:  $(BACKEND_AZURE_STORAGE_ACCOUNT_NAME)
              backendAzureRmContainerName:  $(BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME)
              backendAzureRmKey: 'state.tfstate'
            env:
              ARM_STORAGE_USE_AZUREAD: true
              ARM_USE_AZUREAD: true

          - task: TerraformTaskV4@4
            name: terraformPlan
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out main.tfplan'
              environmentServiceNameAzureRM: $(AZ_SERVICE_CONNECTION)
            env:
              ARM_USE_AZUREAD: true
              TF_VAR_ENVIRONMENT: ${{ parameters.environment }}
```

Error associated:

![Image](https://github.com/user-attachments/assets/697e1f18-c698-4497-9d0b-cad5e8d1b15d)

Any idea would be welcome to help me to fix it.

Thanks,
