### ISSUE TITLE
Error: retrieving Storage Account: 401 token expired

### ISSUE THREAD

**Issue by michvllni** [microsoft/azure-pipelines-terraform#281]
We have a build pipeline that consists of two stages.
Stage 1 does a validation of the project (Terraform init, validate, plan) that also outputs a plan.
Stage 2 waits for approval and then runs Terraform init, apply on the generated plan.

Our project runs on an arm backend.

Our Service Connection uses federated identity to authenticate against azure.

Sometimes, when Job 2 is approved later, the apply fails with the following error:
```
/opt/hostedtoolcache/terraform/1.11.0/x64/terraform apply -auto-approve -input=false ./tfplan.out
╷
│ Error: retrieving Storage Account (Subscription: "<REDACTED>"
│ Resource Group Name: "***"
│ Storage Account Name: "***"): authorizing request: clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS700024: Client assertion is not within its valid time range. Current time: 2025-02-28T06:45:12.1998775Z, assertion valid from 2025-02-28T06:08:20.0000000Z, expiry time of assertion 2025-02-28T06:18:20.0000000Z. Review the documentation at https://learn.microsoft.com/entra/identity-platform/certificate-credentials . Trace ID: 7326281b-3971-4e48-8874-b1b537340100 Correlation ID: 783f7fdd-077d-4dfd-9e1b-ffc490649d94 Timestamp: 2025-02-28 06:45:12Z","error_codes":[700024],"timestamp":"2025-02-28 06:45:12Z","trace_id":"7326281b-3971-4e48-8874-b1b537340100","correlation_id":"783f7fdd-077d-4dfd-9e1b-ffc490649d94","error_uri":"[https://login.microsoftonline.com/error?code=700024"}](https://login.microsoftonline.com/error?code=700024%22})
│ 
│ 
╵
```

My guess is that the token requested for Stage 1 is also used in Stage 2 and not checked if it expired?

Shouldn't the token be validated and refreshed before every command where the backend is used?

Here is our pipeline(very simplified):
```yaml
parameters:
  - name: debugLevel
    displayName: debug level
    type: string
    default: "ERROR"
    values:
      - "TRACE"
      - "DEBUG"
      - "INFO"
      - "WARN"
      - "ERROR"
      - "OFF"
  - name: agentPool
    displayName: agent pool
    type: object
    default: 
      vmImage: 'ubuntu-24.04'

trigger:
  branches:
    include:
      - dev
      - tst
      - main
  paths:
    include:
      - src

variables:
  - name: serviceConnection
    value: 'myServiceConnection'
  - name: keyVaultName
    value: 'myKeyVault'
  - name: env
    value: 'dev'
  - name: tfVersion
    value: '1.10.5'
stages:
  - stage: Validation
    pool: ${{ parameters.agentPool }}
    jobs:
    - job: validate
      displayName: Validation
      variables:
        - name: repoPath
          value: "$(Build.Repository.LocalPath)/$(Build.Repository.Name)"
        - name: sourcesDirectory
          value: 'src'
        - name: debugLevel
          value: ${{ parameters.debugLevel }}
      steps:
      - checkout: self
        fetchDepth: 100
      - task: AzureKeyVault@2.249.1 # get the secrets for the arm backend
        inputs:
          azureSubscription: $(serviceConnection)
          keyVaultName: $(keyVaultName)
          secretsFilter: 'rg-name,sa-name,sc-name'
          runAsPreJob: false
      - task: TerraformInstaller@1.216.33
        inputs:
          terraformVersion: '$(tfVersion)'
      - task: TerraformTaskV4@4
          displayName: 'init'
          env:
            TF_LOG: $(debugLevel)
          inputs:
            workingDirectory: ${{ variables.repoPath }}/${{ variables.sourcesDirectory }}    
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: ${{ variables.serviceConnection }}
            backendAzureRmResourceGroupName: $(rg-name)
            backendAzureRmStorageAccountName: $(sa-name)
            backendAzureRmContainerName: $(sc-name)
            backendAzureRmKey: '$(env).tfstate'
      - task: TerraformTaskV4@4.241.33
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: ${{ variables.repoPath }}/${{ variables.sourcesDirectory }}
      - task: TerraformTaskV4@4
        displayName: 'plan'
        env:
          TF_LOG: $(debugLevel)
        inputs:
          serviceConnection: ${{ variables.serviceConnection }}
          workingDirectory: ${{ variables.repoPath }}/${{ variables.sourcesDirectory }}
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: ${{ variables.serviceConnection }}
          commandOptions: '-out ./tfplan.out -var-file=.env/$env.tfvars -lock-timeout=300s -input=false'
      - task: PublishPipelineArtifact@1.242.0
        displayName: 'Publish plan'
        inputs:
          targetPath: ${{ variables.repoPath }}/${{ variables.sourcesDirectory }}/tfplan.out
          artifact: tfplan
          publishLocation: 'pipeline'

  - stage: Deployment
    pool: ${{ parameters.agentPool }}
    jobs:
    - deployment: 'deploy_state'
      displayName: Deployment
      environment: ${{ variables.env }}
      variables:
        serviceConnection: ${{ variables.serviceConnection }}
        keyVaultName: ${{ variables.keyVaultName }}
        debugLevel: ${{ parameters.debugLevel }}
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureKeyVault@2.249.1 # get the secrets for the arm backend
              inputs:
                azureSubscription: $(serviceConnection)
                keyVaultName: $(keyVaultName)
                secretsFilter: 'rg-name,sa-name,sc-name'
                runAsPreJob: false
            - task: DownloadPipelineArtifact@2.198.0
              displayName: 'Download Artifact tfplan'
              inputs:
                buildType: 'current'
                artifactName: tfplan
                targetPath: ${{ variables.repoPath }}/${{ variables.sourcesDirectory }}
            - task: TerraformInstaller@1.216.33
              inputs:
                terraformVersion: '$(tfVersion)'
            - task: TerraformTaskV4@4
                displayName: 'init'
                env:
                  TF_LOG: $(debugLevel)
                inputs:
                  workingDirectory: ${{ variables.repoPath }}/${{ variables.sourcesDirectory }}    
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: ${{ variables.serviceConnection }}
                  backendAzureRmResourceGroupName: $(rg-name)
                  backendAzureRmStorageAccountName: $(sa-name)
                  backendAzureRmContainerName: $(sc-name)
                  backendAzureRmKey: '$(env).tfstate'
            - task: TerraformTaskV4@4
              displayName: 'apply'
              env:
                TF_LOG: $(debugLevel)
              inputs:
                provider: 'azurerm'
                command: 'apply'
                workingDirectory: ${{ variables.repoPath }}/${{ variables.sourcesDirectory }}    
                environmentServiceNameAzureRM: ${{ variables.serviceConnection }}
                commandOptions: '-auto-approve -input=false ./tfplan.out'
```
