### ISSUE TITLE
How to use TerraformTaskV4 with Workforce Identity Federation to manage GCP project

### ISSUE THREAD

**Issue by Ziemowit-LH** [microsoft/azure-pipelines-terraform#284]
I'm trying to configure Azure DevOps pipeline that uses TerraformTaskV4 with WIF service connection to manage a GCP project.

I have the Service Connection that was working with a PoC pipeline (at least for gcloud commands) of "Azure Resource Manager using workload identity federation with openid connect" type.
Now we'd like to move our Terraform execution in the pipeline to use WiF.

I can't use this service connection directly because it's of the wrong type - only "GCP for Terraform" will work. But these rely on hardcoded service account key, which is not WIF.

Here is the Service Connection config:
```
When creating: App registration or managed identity (manual)
Environment: Azure Cloud
Server URL: management.azure.com
Scope Level: Subscription
Subscription ID: <subscription_id>
Subscription Name: <subscription_name>
Application (client) ID: <client_id>
Directory (tenant) ID: <tenant_id>
Federation Issuer: https://vstoken.dev.azure.com/<organization_id>/
Subject identifier: sc://<org>>/<project>/gcp-wif-test2
```

I got as far as 
```yaml
  - name: ServiceConnection
    value: gcp-wif-test2
  - name: ProjectNumber
    value: 111
  - name: Pool
    value: regula
  - name: Provider
    value: regula
  - name: ServiceAccount
    value: azure-wif-test@project-12345.iam.gserviceaccount.com
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: $(Pipeline.Workspace)/.workload_identity.wlconfig

steps:
- task: AzureCLI@2
  displayName: 'Azure CLI'
  inputs:
    addSpnToEnvironment: true
    azureSubscription: 'gcp-wif-test2'
    connectedServiceNameARM: $(ServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Set the Azure service principal variables
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=false]$servicePrincipalId"
      echo "##vso[task.setvariable variable=ARM_ID_TOKEN;issecret=false]$idToken"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=false]$tenantId"

      # Store the ID token in a file
      echo $idToken > $(Pipeline.Workspace)/.workload_identity.jwt

      # Create the workload identity configuration file for Google Cloud
      cat << EOF > $GOOGLE_APPLICATION_CREDENTIALS
      {
        "type": "external_account",
        "audience": "//iam.googleapis.com/projects/$(ProjectNumber)/locations/global/workloadIdentityPools/$(Pool)/providers/$(Provider)",
        "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
        "token_url": "https://sts.googleapis.com/v1/token",
        "credential_source": {
          "file": "$(Pipeline.Workspace)/.workload_identity.jwt"
        },
        "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/$(ServiceAccount):generateAccessToken"
      }
      EOF

      gcloud projects describe $(ProjectNumber) # this worked

- task: TerraformTaskV4@4
  displayName: init task
  inputs:
    command: init
    provider: gcp
    # backendServiceGCP: 'N/A' # this value is required
    backendGCPBucketName: bucketname
  env:
    GOOGLE_CREDENTIALS_FILE: $(GOOGLE_APPLICATION_CREDENTIALS)
````

This, obviously, fails because the TerraformTaskV4 init requres the backendServiceGCP, which I can't use. And when I do provide it, it uses that identity instead of WIF.
