### ISSUE TITLE
Task V4 custom command stop output to console

### ISSUE THREAD

**Issue by john-warren-dspp** [microsoft/azure-pipelines-terraform#285]
I am having trouble stopping the terraform output appearing in the ADO pipeline logs, even using the custom command and the output directed to a json file.

My code is

- task: TerraformTaskV4@4
    displayName: Terraform Output
    name: terraformOutputv1
     inputs:
      provider: "azurerm"
      command: "custom"
      customCommand: "output"
      commandOptions: "-json"
      outputTo: "file"
      fileName: "terraform_output.json"
      workingDirectory: ${{ parameters.directory }}

**Comment by mericstam** [comment]
Hi, 
The intension of outputTo was not really meant to direct the output to one or the other.  but rather an additional output to file. But agree when looking at it now, it should actually be one or the other or at least the option. 
l will investigate what can be done for supporting this.

br
Manuel

**Comment by steveland83** [comment]
@mericstam (or anyone else who may have used this successfully!) related to the query above, does the file output option normally create files? I've been unable to get it working.

- I note that the automated tests do not appear to cover this scenario ([or any `custom` command](https://github.com/search?q=repo%3Amicrosoft%2Fazure-pipelines-terraform%20custom&type=code))
- I've checked the code base and although there is some code handling the relevant inputs, it looks like the fileName input is [read with incorrect casing](https://github.com/microsoft/azure-pipelines-terraform/blob/main/Tasks/TerraformTask/TerraformTaskV5/src/base-terraform-command-handler.ts#L117), though I couldnt see the implementation of `getInput` so perhaps this is handled in a case safe fashion.

I've run various tests along the lines of the following without any resulting file being created (I'm using the v5 task but the code is the same in both versions):

```
- task: TerraformTask@5
    displayName: Read Terraform Outputs
    inputs:
      provider: azurerm
      command: output
      workingDirectory: ${{ parameters.workingDirectory }}
      outputFormat: json
      outputTo: file
      fileName: terraform_output.json
      environmentServiceNameAzureRM: [redacted]
  - bash: |
      #try to find the terraform_output.json file
      echo "find:"
      echo $(find -name "*terraform_output*" -type f)
```

I've tried using lowercase `filename` and a few other variations of the inputs but the subsequent bash step never finds any matching files.

*While I'm here, I should also mention that the inability to supress console writes of the output will be a real problem for users who may have sensitive values in the collection (aka...me), so I'll be eagerly watching this!
