### ISSUE TITLE
4.241.34  Failed to find terraform tool in paths

### ISSUE THREAD

**Issue by greengumby** [microsoft/azure-pipelines-terraform#294]
Running init with the latest version causes the error 

Failed to find terraform tool in paths

`##[debug]check path : /home/vsts/work/_tasks/TerraformTaskV4_fe504acc-6115-40cb-89ff-191386b5e7bf/4.241.34/node_modules/azure-pipelines-tasks-artifacts-common/module.json
##[debug]adding resource file: /home/vsts/work/_tasks/TerraformTaskV4_fe504acc-6115-40cb-89ff-191386b5e7bf/4.241.34/node_modules/azure-pipelines-tasks-artifacts-common/module.json
##[debug]system.culture=en-US
##[debug]check path : /home/vsts/work/_tasks/TerraformTaskV4_fe504acc-6115-40cb-89ff-191386b5e7bf/4.241.34/task.json
##[debug]adding resource file: /home/vsts/work/_tasks/TerraformTaskV4_fe504acc-6115-40cb-89ff-191386b5e7bf/4.241.34/task.json
##[debug]system.culture=en-US
##[debug]provider=azurerm
##[debug]command=init
##[debug]workingDirectory=/home/vsts/work/1/s/azuredevops/devops/terraform/
##[debug]commandOptions=undefined
##[debug]which 'terraform'
##[debug]not found
##[debug]task result: Failed
##[error]Error: Failed to find terraform tool in paths
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]Error: Failed to find terraform tool in paths
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Failed to find terraform tool in paths
`

**Comment by greengumby** [comment]
Hi, yes running MS hosted Ubuntu.  I am not specifically running any terraform installer.  This has been running smoothly for a while now so maybe there is a breaking change?

      ```
  - task: TerraformTaskV4@4
          displayName: 'init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: '$(azure_service_ARM)'
            backendAzureRmResourceGroupName: '$(azure_terraform_resourcegroup)'
            backendAzureRmStorageAccountName: '$(azure_terraform_storage)'
            backendAzureRmContainerName: '$(azure_terraform_state)'
            backendAzureRmKey: '$(azure_terraform_storagebackendAzureRmKey)'
            workingDirectory: $(pathToTerraform)
```
