### ISSUE TITLE
Documentation for task v4 is incomplete - hard to get show command to work

### ISSUE THREAD

**Issue by Noel-Jones** [microsoft/azure-pipelines-terraform#295]
In order to get the `show` command to work I had to specify the following:

````
- task: TerraformTaskV4@4
  name: show_ci
  displayName: 'Terraform Show'
  condition: and(succeeded(), eq(variables['plan_ci.changesPresent'], 'true'), eq(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: show
    outputFormat: json
    outputTo: file
    fileName: ${{ parameters.WorkingDirectory }}/${{ parameters.TfPlanOutputName }}.json
    workingDirectory: ${{ parameters.WorkingDirectory }}
    environmentServiceNameAzureRM: ${{ parameters.AzureManagementGroupServiceConnectionName }}
    commandOptions: '${{ parameters.TfPlanOutputName }}.plan'
````

Of note:

- there is no reference to `fileName` in the documentation
- the filename is not relative to the working directory (arguably a bug)
