### ISSUE TITLE
TerraformTaskV1@0 init without backendServiceArm using -backend=false

### ISSUE THREAD

**Issue by chris-b-chalmers** [microsoft/azure-pipelines-terraform#30]
I am looking to have a pipeline which only runs a Terraform install, Terraform init then Terraform validate. This works normally when I specify my backendServiceArm, backendAzureRmResourceGroupName, backendAzureRmStorageAccountName, backendAzureRmContainerName and backendAzureRmKey inputs. 

    - task: TerraformTaskV1@0
      displayName: 'Terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: '$(backendServiceArm)'
        backendAzureRmResourceGroupName: '$(backendAzureRmResourceGroupName)'
        backendAzureRmStorageAccountName: '$(backendAzureRmStorageAccountName)'
        backendAzureRmContainerName: '$(backendAzureRmContainerName)'
        backendAzureRmKey: '$(backendAzureRmKey)'

I'm aiming to remove the backend configuration so that I dont need to grant this pipeline access into Azure, and any validation can be done only within Azure DevOps. 

I have tried combinations of the following but it always errors with "**##[error]Error: Input required: backendServiceArm**"

    - task: TerraformTaskV1@0
      displayName: 'Terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: -backend=false

Is there a way to accomplish this using the extension?

**Comment by i-am-shodan** [comment]
+1 for this

**Comment by p0onage** [comment]
I found a better work around for me. I populated the required fields with N/A and put `-backend=false` as a command option. This allows me to init locally for the build step then I can init remote for my specific environment branches. 

`- task: TerraformTaskV3@3
  displayName: 'Terraform init test'
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '-input=false -backend=false'
    workingDirectory: '${{parameters.tf_path}}'
    backendServiceArm:  '${{parameters.tf_azurerm}}'
    backendAzureRmResourceGroupName: 'N/A'
    backendAzureRmStorageAccountName: 'N/A'
    backendAzureRmContainerName: 'N/A'
    backendAzureRmKey: 'N/A'
    `

In my dev, qa and production stages I just need to remove the .terraform folder to make sure I don't get the error "migrate state needed"

` rm -rf directoryname $(Pipeline.Workspace)/terraform/.terraform`

**Comment by victorfrye** [comment]
+1 for this. Believe it's an issue as of v4 still.

**Comment by jaredfholgate** [comment]
I'm not sure of the exact use case here? The purpose of the Task is to simplify using a Service Connection with Terraform. It is designed for running Terraform with connections to Cloud providers. 

If you are just running a local fmt / validate you don't need the task or a Service Connection. It actually makes it more complicated than it needs to be. I appreciate the Task could be updated to handle this edge case more gracefully, but in the meantime you can just use the standard CLI tooling.

E.g. 
```yaml
jobs:
  - job: validate
    displayName: Validate Terraform
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - pwsh: terraform fmt -check
        displayName: Terraform Format Check
      - pwsh: terraform init -backend=false
        displayName: Terraform Init
      - pwsh: terraform validate
        displayName: Terraform Validate
```

Example taken from [here](https://github.com/Azure/alz-terraform-accelerator/blob/b064264b6d57232dbde6f203cfe1f368e51fdac4/templates/ci_cd/azuredevops/templates/ci.yaml#L8).
