### ISSUE TITLE
AKS Authentication K8 Provider Docs

### ISSUE THREAD

**Issue by PvH-SPC** [microsoft/azure-pipelines-terraform#308]
Hi,

Can we create docs on how to authenticate the Kubernetes provider alongside the azure RM.  The issue is that we have three service connections, respectively the first two work fine, for backend storage and the azure rm for plan/apply steps.  Without access to AKS this works great, however to authenticate to AKS we have a 3rd service connection, which works fine for standalone tasks (eg azurecli, helm, Kubernetes etc), but as it turns out ive spent a huge amount of time trying to get the proper credentials in place, using the kubeconfig file, and other means to have the terraform plan and apply pipelines able to do both azure and Kubernetes connections.  I can do it via --admin connection, but that requires local accounts and doesn't use the azure rbac / service connections.  If you generate the config file in the azurecli step, and expose it, the issue is that the azure cli terminates the connection so the authentication breaks in the next terraform step.  Here is some sample code:

```
 - task: KubectlInstaller@0
                  displayName: 'Install kubectl'
                  inputs:
                    kubectlVersion: 'latest'   # You can specify a version like '1.26.3' if you need
                - task: AzureCLI@2
                  displayName: "Get AKS kubeconfig"
                  inputs:
                    azureSubscription: '${{ parameters.envConfigMap[pair.key].asc }}'
                    scriptType: bash 
                    scriptLocation: inlineScript
                    inlineScript: | 
                      az aks get-credentials --resource-group rg-containers-eus2 --name ${{ parameters.envConfigMap[pair.key].aksClusterName }} --file $(Build.SourcesDirectory)/kubeconfig
                      kubelogin convert-kubeconfig -l azurecli --kubeconfig $(Build.SourcesDirectory)/kubeconfig
                      export KUBECONFIG=$(Build.SourcesDirectory)/kubeconfig
                      cat $(Build.SourcesDirectory)/kubeconfig
                      kubectl get pods -n ourapps
```

```
     - task: TerraformTaskV4@4
            name: terraformPlan
            displayName: terraform plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '${{ parameters.terraformDirectory }}'
              commandOptions: '-input=false -detailed-exitcode -var="kubeconfig_path=$(Build.SourcesDirectory)/kubeconfig" -var-file=../variables/${{ workload }}/${{ pair.key }}.tfvars -out=plan.tfplan'
              environmentServiceNameAzureRM: 'app-lz-${{ pair.key }}'
            env:
              KUBECONFIG: $(Build.SourcesDirectory)/kubeconfig
          - bash: |
```

```

variable "kubeconfig_path" {
  type = string
}

provider "kubernetes" {
  config_path = "/agent/_work/1/s/kubeconfig"#var.kubeconfig_path

  # host                   = data.azurerm_kubernetes_cluster.aks.kube_config.0.host
  # cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.cluster_ca_certificate)
  
  # exec {
  #   api_version = "client.authentication.k8s.io/v1beta1"
  #   command     = "kubelogin"
  #   args = [
  #     "get-token",
  #     "--login",
  #     "azurecli",
  #     "--server-id",
  #     "6dae42f8-4368-4678-94ff-3960e28e3630" # This is the default AAD server ID for AKS
  #   ]
  # }


}
```
