### ISSUE TITLE
Cancel TF Apply breaks state

### ISSUE THREAD

**Issue by NArnott** [microsoft/azure-pipelines-terraform#31]

**Comment by Bouke** [comment]
I'm running on `ubuntu-latest` and have the same issue. Cancelling should allow terraform to quit gracefully. Strange that this hasn't been addressed in the 3.5 years since it was reported. We're paying customers of Microsoft; can we expect some support here?

**Comment by MoussaBangre** [comment]
facing the same problem and very anoying for the production pipeline. Any workaround/Solution to that ?

**Comment by Bouke** [comment]
We're at 4.75 years now without any feedback / support. 👎

**Comment by mericstam** [comment]
As you might already know @Bouke this issue is not specific to the terraform extension tasks.  There is a linked issue that explains in more detail, but unfortunately no solution exists as far as i understand.
Br
Manuel

**Comment by Bouke** [comment]
It seems the upstream issue has been addressed a year ago with https://github.com/microsoft/azure-pipelines-agent/pull/4744 and the issue tracking it has been closed today: https://github.com/microsoft/azure-pipelines-agent/issues/4364#issuecomment-2728784518.

**Comment by mericstam** [comment]
ok. i was under the impression that setting the env variables did not have any effect.
did you try to set env variables in the job before running the task? as the comment suggested?

br
Manuel

**Comment by michvllni** [comment]
I just tried it in Azure DevOps Services.

I set the env variables on the job level and the pipeline recognized them, but did not do a graceful shutdown:

![Image](https://github.com/user-attachments/assets/b686b7d5-8c58-42df-8071-0ed756b202f1)

```yml
jobs:
- job: validate
  displayName: Validation
  variables:
    - name: PROCESS_SIGINT_TIMEOUT
      value: 30000
    - name: PROCESS_SIGTERM_TIMEOUT
      value: 30000
    - name: USE_GRACEFUL_PROCESS_SHUTDOWN
      value: true
...
```

When cancelling the build, it immediately cancels and the state remains in leased state:

![Image](https://github.com/user-attachments/assets/277e681a-a498-4d4a-8a2b-2e1cf9598d8f)

I also tried setting these variables on the plan step level but it had no effect there as well:
```yml
  - task: TerraformTaskV4@4
    displayName: 'plan'
    env:
      TF_LOG: $(debugLevel)
      PROCESS_SIGINT_TIMEOUT: 30000
      PROCESS_SIGTERM_TIMEOUT: 30000
    inputs:
      serviceConnection: ${{ parameters.serviceConnection }}
      workingDirectory: ${{ parameters.repoPath }}/${{ parameters.sourcesDirectory }}
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: ${{ parameters.serviceConnection }}
      commandOptions: $(plan-args) # gets set via script step before
```

**Comment by michaelg-baringa** [comment]
We've been facing this issue for a while and more so now as developers are pushing changes more frequently

**Comment by arichesson** [comment]
Instead of `TerraformTaskV4@4`, I switched to running `terraform plan` through the basic bash task. Make sure you allow for a longer shutdown time by setting the job variables:
```yaml
- job: TerraformPlan
  displayName: "Terraform Plan"
  variables:
     PROCESS_SIGINT_TIMEOUT: 30000
     PROCESS_SIGTERM_TIMEOUT: 30000
  steps:
  - bash: | 
      terraform plan ...
```
Referencing the azure devops github issue:
https://github.com/microsoft/azure-pipelines-agent/issues/4364
