### ISSUE TITLE
TerraformTaskV3 support for workspace?

### ISSUE THREAD

**Issue by jvangeete** [microsoft/azure-pipelines-terraform#66]
In trying to help with [this question](https://stackoverflow.com/questions/72398912/unable-to-select-terraform-workspace-in-azure-devops-pipeline), I noticed in the V3 README that the word `workspace` does not exist.  Does that mean tasks like 
```
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
            inputs:
              provider: aws
              command: custom
              customCommand: 'workspace select devstage'
```
should expect to see an exit code 127 (job's command can not be found or executed)?
