### ISSUE TITLE
Error: Endpoint data parameter not present: subscriptionid using management group scoped spn

### ISSUE THREAD

**Issue by ChrisTav424** [microsoft/azure-pipelines-terraform#81]
We are using the Terraform@V3 task to deploy infrastructure at the management group level (Tenant Root Group). The following is the pipeline yaml. 

```
trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\caf'
    backendServiceArm: 'devops (73e0699d-f086-4960-8b97-abad78a39916)'
    environmentServiceNameAzureRM: 'tf-connect-manual'
    backendAzureRmResourceGroupName: 'rg-storage-terraform'
    backendAzureRmStorageAccountName: 'terraform2319'
    backendAzureRmContainerName: 'terraform-state'
    backendAzureRmKey: '<secret removed>'

- task: TerraformTaskV3@3
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\caf'
    environmentServiceNameAzureRM: 'tf-connect-manual'
```

- Running the tf code locally using az login (works fine). 
- environmentServiceNameAzureRM: a service connection that is subscription scoped (works fine)
- environmentServiceNameAzureRM: a service connection that is management group scoped (doesn't work - error below)

<img width="574" alt="image" src="https://user-images.githubusercontent.com/44398463/184892734-61327c69-352b-402b-881d-880c5f552144.png">

This is where we are setting the different service connection scopes

![image](https://user-images.githubusercontent.com/44398463/184893513-26ca6f13-595e-4794-9d35-635729e57741.png)

How do we get past this error?
