### ISSUE TITLE
In V3 output variables are no longer there.

### ISSUE THREAD

**Issue by Apholisha** [microsoft/azure-pipelines-terraform#83]
In V3 output variables are no longer there.

example:
```
          - task: TerraformTaskV1@3
            displayName: 'Terraform Apply'
            name: 'TerraformApply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Infrastructure/'
              environmentServiceNameAzureRM: '${{ parameters.azureSubscription }}'


          - task: PowerShell@2
            name: VarDeclaration
            displayName: Declare Terraform outputs as variables
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Declaring all Terraform outputs as variables"
                Write-Host "$(TerraformApply.jsonOutputVariablesPath)"
```
This fails with 

```
+ Write-Host "$(TerraformApply.jsonOutputVariablesPath)"
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TerraformApply.jsonOutputVariablesPath:String) [], ParentContainsErrorR 
   ecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I've tested with V2 of the apply task and that worked
