### ISSUE TITLE
Terraform workspace support

### ISSUE THREAD

**Issue by MDUYN** [microsoft/azure-pipelines-terraform#85]
I am looking to have a pipeline  which selects a Terraform workspace, similar like the instructions below.

`      
- task: TerraformTaskV1@0
        displayName: 'apply terraform'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workspace: <SELECTED_WORKSPACE>
          customCommand: 'workspace'
          commandOptions: '-input=false -var-file="$(System.DefaultWorkingDirectory)/infrastructure/azure/vars/default.tfvars"'
          environmentServiceNameAzureRM: '${{ variables.backendServiceArm }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/azure'
`
Could this functionality please be added to the terraform extension.

**Comment by mericstam** [comment]
Hi, I  will take a look and provide an example how to work with workspaces.

**Comment by MDUYN** [comment]
That would be great!

**Comment by mericstam** [comment]
Hi, I think you need to select the workspace first and then do apply. Perhaps something like this: 

```code 
- task: TerraformTaskV3@3
        displayName: 'select workspace'
        inputs:
          provider: 'azurerm'
          command: 'custom'
          customCommand: 'workspace'
          commandOptions: 'select <SELECTED_WORKSPACE>'
          outputTo: 'console'
          environmentServiceNameAzureRM: '${{ variables.backendServiceArm }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/azure'

- task: TerraformTaskV3@3
        displayName: 'apply terraform'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '-input=false -var-file="$(System.DefaultWorkingDirectory)/infrastructure/azure/vars/default.tfvars"'
          environmentServiceNameAzureRM: '${{ variables.backendServiceArm }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/azure'

**Comment by jz-wilson** [comment]
I have been using the TF_WORKSPACE variable as a workaround.

```yaml
- task: TerraformTaskV3@3
        displayName: 'apply terraform'
        env:
          TF_WORKSPACE: <WORKSPACE>
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: '-input=false -var-file="$(System.DefaultWorkingDirectory)/infrastructure/azure/vars/default.tfvars"'
          environmentServiceNameAzureRM: '${{ variables.backendServiceArm }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure/azure' 
```
